In [95]:
import numpy as np

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

In [96]:
arr=np.array([1, 2, 3, 6, 4,5])
arr2=arr[::-1]
arr2

array([5, 4, 6, 3, 2, 1])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
NumPy in-built methods 

In [97]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
#Method 1
print(array1.reshape(9,))
#Method 2
print(array1.flatten())



[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 

In [98]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
if np.array_equal(arr1, arr2):
    print("Equal")
else:
    print("Not Equal")

Equal


(d) Find the most frequent value and their indice(s) in the following arrays: 
i. 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [99]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
# for x
values,counts=np.unique(x,return_counts=True)
print("Values:", values)
print("Counts:", counts) 
print("Most frequent values:",values[counts==counts.max()])
indices=np.where(np.isin(x,values[counts==counts.max()]))
print("Indices of most frequent values:", indices)
# for y
values,counts=np.unique(y,return_counts=True)
print("Values:", values)
print("Counts:", counts) 
print("Most frequent values:",values[counts==counts.max()])
indices=np.where(np.isin(y,values[counts==counts.max()]))
print("Indices of most frequent values:", indices)


Values: [1 2 3 4 5]
Counts: [5 2 1 1 1]
Most frequent values: [1]
Indices of most frequent values: (array([0, 5, 7, 8, 9]),)
Values: [1 2 3 4]
Counts: [3 2 3 2]
Most frequent values: [1 3]
Indices of most frequent values: (array([0, 1, 2, 4, 8, 9]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
i. Sum of all elements 
ii. Sum of all elements row-wise  
iii. Sum of all elements column-wise 

In [100]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg.sum())

print(gfg.sum(axis=1))

print(gfg.sum(axis=0))


45
[[14]
 [16]
 [15]]
[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
i. Sum of diagonal elements 
ii. Eigen values of matrix 
iii. Eigen vectors of matrix 
iv. Inverse of matrix 
v. Determinant of matrix

In [101]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
# i. Sum of diagonal elements
n_array_diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", n_array_diagonal_sum)

# ii. Eigen values of matrix
eigenvalues,eigenvectors=np.linalg.eig(n_array)
print("Eigen values of matrix:",eigenvalues)
# iii. Eigen vectors of matrix
print("Eigen vectors of matrix:", eigenvectors) 
# iv. Inverse of matrix
inverse_matrix=np.linalg.inv(n_array)
print("Inverse of matrix:\n",inverse_matrix)

# v. Determinant of matrix
determinant=np.linalg.det(n_array)
print("Determinant of matrix:",determinant)



Sum of diagonal elements: 176
Eigen values of matrix: [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy: 
i. 
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]] 
ii. 
p = [[1, 2], [2, 3], [4, 5]] 
q = [[4, 5, 1], [6, 7, 2]] 

In [102]:
p=np.matrix([[1,2],[2,3]])
q=np.matrix([[4,5],[6,7]])
print("product is \n",p*q)


p=np.matrix([[1,2],[2,3],[4,5]])
q=np.matrix([[4,5,1],[6,7,2]])
print("product is \n",np.dot(p,q))

product is 
 [[16 19]
 [26 31]]
product is 
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product? 

In [103]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print()
print(np.outer(x,y))
print()
cartesian_product = []

for i in range(x.shape[0]):
    for j in range(y.shape[0]):
        combined = np.concatenate((x[i], y[j]))
        cartesian_product.append(combined)

cartesian_product = np.array(cartesian_product)
print("Cartesian Product using loop:\n", cartesian_product)



[[17 52]
 [13 62]]

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product using loop:
 [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
i. Find element-wise absolute value 
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row. 
iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row 




In [104]:
array=np.array([[1,-2,3],[-4,5,-6]])
abs_array=np.array(np.abs(array))
print("Element-wise absolute value:\n", abs_array)

flat=array.flatten()
p25=np.percentile(flat,25)
p50=np.percentile(flat,50)
p75=np.percentile(flat,75)
print("25th percentile:", p25)
print("50th percentile:", p50)  
print("75th percentile:", p75)


# for each coloum
p25_col=np.percentile(array,25,axis=0)
p50_col=np.percentile(array,50,axis=0)
p75_col=np.percentile(array,75,axis=0)
print("25th percentile for each column:", p25_col)
print("50th percentile for each column:", p50_col)
print("75th percentile for each column:", p75_col)


# for each row
p25_row=np.percentile(array,25,axis=1)
p50_row=np.percentile(array,50,axis=1)
p75_row=np.percentile(array,75,axis=1)
print("25th percentile for each row:", p25_row)
print("50th percentile for each row:", p50_row)
print("75th percentile for each row:", p75_row)


# Mean ,Median,Standard Deviation for flattened array

mean=np.mean(flat)
median=np.median(flat)
std_dev=np.std(flat)

print("Mean:",mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

# Mean, Median, and Standard Deviation for each column
mean=np.mean(array,axis=0)
median=np.median(array,axis=0)
std_dev=np.std(array,axis=0)

print("Mean:",mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


#Mean, Median, and Standard Deviation for each row
mean=np.mean(array,axis=1)
median=np.median(array,axis=1)
std_dev=np.std(array,axis=1)

print("Mean:",mean)
print("Median:", median)
print("Standard Deviation:", std_dev)



Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
25th percentile: -3.5
50th percentile: -0.5
75th percentile: 2.5
25th percentile for each column: [-2.75 -0.25 -3.75]
50th percentile for each column: [-1.5  1.5 -1.5]
75th percentile for each column: [-0.25  3.25  0.75]
25th percentile for each row: [-0.5 -5. ]
50th percentile for each row: [ 1. -4.]
75th percentile for each row: [2.  0.5]
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values 


In [105]:
a=np.array([-118,-16,-0.5,0.5,1.6,1.8,3.0])
#add print statements to see the results
print("Floor values:", np.floor(a))
print("Ceiling values:", np.ceil(a))    
print("Truncated values:", np.trunc(a))
print("Rounded values:", np.rint(a))


Floor values: [-118.  -16.   -1.    0.    1.    1.    3.]
Ceiling values: [-118.  -16.   -0.    1.    2.    2.    3.]
Truncated values: [-118.  -16.   -0.    0.    1.    1.    3.]
Rounded values: [-118.  -16.   -0.    0.    2.    2.    3.]


(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i. Sorted array 
ii. Indices of sorted array 
iii. 4 smallest elements 
iv. 5 largest elements

In [106]:
array=np.array([10,52,62,16,16,54,453])

array_sort=np.sort(array)
indices_sorted=np.argsort(array)
print("Sorted array:", array)
print("Indices of sorted array:", indices_sorted)
print("4 smallest elements:",array_sort[0:4])
print("5 largest elements:", array_sort[-5:])


Sorted array: [ 10  52  62  16  16  54 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


For the array=np.array([1.0,1.2,2.2,2.0,3.0,2.0]), find
1. Integer elements only
2. Float elements only

In [107]:
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
int_elements=array[array==array.astype(int)]
float_elements=array[array!=array.astype(int)]

print("Integer elements only:",int_elements)
print("Float elements array only:",float_elements)


Integer elements only: [1. 2. 3. 2.]
Float elements array only: [1.2 2.2]


Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images) 

In [108]:
import numpy as np
import cv2 as cv

def img_to_array(image_path):
    image=cv.imread(image_path)

    image_gray=cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    image_array=np.array(image)
    gray_array=np.array(image_gray)

    if len(gray_array.shape) == 2:
        np.savetxt('gray_array.txt', gray_array, fmt='%d')
        print("Gray array saved to gray_array.txt")
    else:
        print("Gray array is not 2D, cannot save to file.")
    if len(image_array.shape) == 3:
        np.savetxt('image_array.txt', image_array.reshape(-1, image_array.shape[2]), fmt='%d')
        print("Image array saved to image_array.txt")

    else:
        print("Image array is not 3D, cannot save to file.")
        
img_to_array("D:\\Wallpaper\\5.jpg")

Gray array saved to gray_array.txt
Image array saved to image_array.txt
